/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:ae0f35cd7c78cc21175d7c9ef94a9903:b04190bff7fadd386f5d060868d199f4:448d9847c0b63317007a0aa1fa13ac55$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class unsaved
	{
		public const string Stick_jump_right_01 = "stick_jump_right_01";
		public const string Stick_stand = "stick_stand";
		public const string Stick_walk_right_01 = "stick_walk_right_01";
		public const string Stick_walk_right_02 = "stick_walk_right_02";
	}
}