/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:9599556562ce8a3cef21db0ab0bb40d1:246b1fb3a70e82f8a3ca6c4a90f809c9:8658243ef10bf71dfc6586cfcb380105$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class TestTerraAtlas
	{
		public const string Sprite_01 = "01";
		public const string Sprite_02 = "02";
		public const string Sprite_03 = "03";
		public const string Sprite_04 = "04";
		public const string Sprite_05 = "05";
		public const string Sprite_06 = "06";
		public const string Sprite_07 = "07";
		public const string Sprite_08 = "08";
		public const string Sprite_09 = "09";
	}
}