/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:0c64640304e721d77e4e8caa097f536a:5b61bbe154a3687070cf73951a84c9d6:474670d38e62ac76189184b0ba8e9b35$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public static class CafeTileset
	{
		public const string Barrel = "barrel";
		public const string BrickBlock = "brick-block";
		public const string BrickGrey = "brick-grey";
		public const string CarpetLeft = "carpet-left";
		public const string CarpetMiddle = "carpet-middle";
		public const string CarpetRight = "carpet-right";
		public const string ChairFaceLeft = "chair-face-left";
		public const string ChairFaceRight = "chair-face-right";
	}
}