/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:61a6abb3f44ac2fc169f5e14bc7fdf00:0808f5799c48305709cfa3bfa655c5d1:3c890887f31976f1be43c9ba6ae4dbe2$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public static class EffectsSheet
	{
		public const string RoundExplosion01 = "RoundExplosion01";
		public const string RoundExplosion02 = "RoundExplosion02";
		public const string RoundExplosion03 = "RoundExplosion03";
		public const string RoundExplosion04 = "RoundExplosion04";
		public const string RoundExplosion05 = "RoundExplosion05";
	}
}