/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:a14e7bfb38fc9c7e4dd92e85acc8ea22:7160de77e95b1bda2ae01ee4925a10a0:448d9847c0b63317007a0aa1fa13ac55$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class StickSheet
	{
		public const string StickPunch1 = "StickPunch1";
		public const string StickPunch2 = "StickPunch2";
		public const string StickPunch3 = "StickPunch3";
		public const string StickRightJump01 = "StickRightJump01";
		public const string StickStand = "StickStand";
		public const string StickWalkRight01 = "StickWalkRight01";
		public const string StickWalkRight02 = "StickWalkRight02";
		public const string StickWalkRight03 = "StickWalkRight03";
	}
}