/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:c850b5a6d529b65e097d861b0c7749f0:c2c120529d77b0b45fcfad425984e8fe:ae8e2302e56d258f62c06a401261bfd3$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class TestTerraAtlas
	{
		public const string TerraArmRaise = "terra_arm_raise";
		public const string TerraStandDown = "terra_stand_down";
		public const string TerraStandLeft = "terra_stand_left";
		public const string TerraStandUp = "terra_stand_up";
		public const string TerraWalkUp01 = "terra_up_walk_01";
		public const string TerraWalkDown01 = "terra_walk_down_01";
		public const string TerraWalkDown02 = "terra_walk_down_02";
		public const string TerraWalkLeft01 = "terra_walk_left_01";
		public const string TerraWalkLeft02 = "terra_walk_left_02";
		public const string TerraWalkUp02 = "terra_walk_up_02";
	}
}