/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:bad22a88b3fc965922043658852d09d2:b132e5c7bf77a3ea0aa30a1362381f18:448d9847c0b63317007a0aa1fa13ac55$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class unsaved
	{
		public const string Stick_jump_right_01 = "stick_jump_right_01";
		public const string Stick_stand = "stick_stand";
		public const string Stick_walk_right_01 = "stick_walk_right_01";
		public const string Stick_walk_right_02 = "stick_walk_right_02";
	}
}